// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCAKcROU0g8qaS6mI2m_7bwbyGl_m5Yc',
    appId: '1:1076863044360:web:08de7a33f350bf78c4babd',
    messagingSenderId: '1076863044360',
    projectId: 'barb-cut',
    authDomain: 'barb-cut.firebaseapp.com',
    storageBucket: 'barb-cut.firebasestorage.app',
    measurementId: 'G-9M5HRVH5VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsb3XiCtFqy3UqNRYH7Q8XdLHUjGjJT_U',
    appId: '1:1076863044360:android:33d3352d186fb3c3c4babd',
    messagingSenderId: '1076863044360',
    projectId: 'barb-cut',
    storageBucket: 'barb-cut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKOkspZj7YkVPG3kMk2P-4O-m3IR7gzRE',
    appId: '1:1076863044360:ios:583b7514779ce854c4babd',
    messagingSenderId: '1076863044360',
    projectId: 'barb-cut',
    storageBucket: 'barb-cut.firebasestorage.app',
    iosBundleId: 'io.github.ishanlahiru.barbcut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKOkspZj7YkVPG3kMk2P-4O-m3IR7gzRE',
    appId: '1:1076863044360:ios:583b7514779ce854c4babd',
    messagingSenderId: '1076863044360',
    projectId: 'barb-cut',
    storageBucket: 'barb-cut.firebasestorage.app',
    iosBundleId: 'io.github.ishanlahiru.barbcut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKCAKcROU0g8qaS6mI2m_7bwbyGl_m5Yc',
    appId: '1:1076863044360:web:855c09907c7e37acc4babd',
    messagingSenderId: '1076863044360',
    projectId: 'barb-cut',
    authDomain: 'barb-cut.firebaseapp.com',
    storageBucket: 'barb-cut.firebasestorage.app',
    measurementId: 'G-8LYS6GBKGZ',
  );
}
